import type { CatalogEntry } from '../catalog-types'

const VALID_FROM = '2023-01-01'

export const TAX_CATALOG: CatalogEntry[] = [
  {
    code: 'VAT_MONTHLY_RETURN',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'CIVA art. 41.º',
    appliesWhen: { all: [{ field: 'hasOpenActivity', op: 'eq', value: true }, { field: 'vatRegime', op: 'eq', value: 'MONTHLY' }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 20, monthsAfter: 2 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Declaração periódica de IVA', description: 'Regime mensal' },
      en: { name: 'Declaração periódica de IVA', description: 'Monthly VAT return' },
    },
  },
  {
    code: 'VAT_QUARTERLY_RETURN',
    authority: 'TAX',
    periodicity: 'QUARTERLY',
    legalRef: 'CIVA art. 41.º',
    appliesWhen: { all: [{ field: 'hasOpenActivity', op: 'eq', value: true }, { field: 'vatRegime', op: 'eq', value: 'QUARTERLY' }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 20, monthsAfter: 2 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Declaração periódica de IVA', description: 'Regime trimestral' },
      en: { name: 'Declaração periódica de IVA', description: 'Quarterly VAT return' },
    },
  },
  {
    code: 'VAT_PAYMENT_MONTHLY',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'CIVA art. 27.º',
    appliesWhen: { all: [{ field: 'hasOpenActivity', op: 'eq', value: true }, { field: 'vatRegime', op: 'eq', value: 'MONTHLY' }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 25, monthsAfter: 2 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento de IVA', description: 'Regime mensal' },
      en: { name: 'Pagamento de IVA', description: 'Monthly VAT payment' },
    },
  },
  {
    code: 'VAT_PAYMENT_QUARTERLY',
    authority: 'TAX',
    periodicity: 'QUARTERLY',
    legalRef: 'CIVA art. 27.º',
    appliesWhen: { all: [{ field: 'hasOpenActivity', op: 'eq', value: true }, { field: 'vatRegime', op: 'eq', value: 'QUARTERLY' }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 25, monthsAfter: 2 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento de IVA', description: 'Regime trimestral' },
      en: { name: 'Pagamento de IVA', description: 'Quarterly VAT payment' },
    },
  },
  {
    code: 'EFATURA_INVOICE_REPORTING',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'Decreto-Lei n.º 198/2012',
    appliesWhen: { all: [{ field: 'hasOpenActivity', op: 'eq', value: true }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 5, monthsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Comunicação de faturas (e-Fatura)', description: 'Comunicação mensal à AT' },
      en: { name: 'Comunicação de faturas (e-Fatura)', description: 'Monthly invoice reporting to the tax authority' },
    },
  },
  {
    code: 'DMR_AT',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'CIRS art. 119.º',
    // Owner review: confirm this is genuinely distinct from SS_REMUNERATION_DECLARATION
    // (social-security.ts) — the master table lists them as two separate codes.
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 10, monthsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Declaração Mensal de Remunerações (AT)', description: 'Retenções na fonte sobre rendimentos do trabalho' },
      en: { name: 'Declaração Mensal de Remunerações (AT)', description: 'Monthly withholding declaration to the tax authority' },
    },
  },
  {
    code: 'WITHHOLDING_TAX_PAYMENT',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'CIRS art. 98.º',
    // Owner review: master table's "applies to" column says "company"; this
    // conditions on hasWithholding instead, since that field exists
    // specifically to drive this rule and can also apply to an individual
    // with employees.
    appliesWhen: { all: [{ field: 'hasWithholding', op: 'eq', value: true }] },
    deadline: { kind: 'dayOfMonthAfterPeriodEnd', day: 20, monthsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento de retenções na fonte', description: 'Entrega mensal ao Estado' },
      en: { name: 'Pagamento de retenções na fonte', description: 'Monthly withholding tax payment' },
    },
  },
  {
    code: 'MODEL_22_CIT_RETURN',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIRC art. 120.º',
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 5, day: 31, yearsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Modelo 22', description: 'Declaração anual de IRC' },
      en: { name: 'Modelo 22', description: 'Annual corporate income tax return' },
    },
  },
  {
    code: 'IES_ANNUAL_FILING',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'Decreto-Lei n.º 8/2007',
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 7, day: 15, yearsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'IES', description: 'Informação Empresarial Simplificada' },
      en: { name: 'IES', description: 'Simplified corporate information return' },
    },
  },
  {
    code: 'CIT_PAYMENT_ON_ACCOUNT_1',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIRC art. 104.º',
    // Owner review: exact day not given in the master spec's table
    // ("July, September, 15 December") — encoded as the last day of July.
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 7, day: 31, yearsAfter: 0 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento por conta de IRC (1.º)', description: 'Primeira prestação' },
      en: { name: 'Pagamento por conta de IRC (1.º)', description: 'First CIT payment on account' },
    },
  },
  {
    code: 'CIT_PAYMENT_ON_ACCOUNT_2',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIRC art. 104.º',
    // Owner review: exact day not given — encoded as the last day of September.
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 9, day: 30, yearsAfter: 0 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento por conta de IRC (2.º)', description: 'Segunda prestação' },
      en: { name: 'Pagamento por conta de IRC (2.º)', description: 'Second CIT payment on account' },
    },
  },
  {
    code: 'CIT_PAYMENT_ON_ACCOUNT_3',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIRC art. 104.º',
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 12, day: 15, yearsAfter: 0 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Pagamento por conta de IRC (3.º)', description: 'Terceira prestação (pagamento especial)' },
      en: { name: 'Pagamento por conta de IRC (3.º)', description: 'Third CIT payment on account' },
    },
  },
  {
    code: 'MODEL_10_INCOME_WITHHOLDING',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIRS art. 119.º',
    // Owner review: same hasWithholding reasoning as WITHHOLDING_TAX_PAYMENT above.
    appliesWhen: { all: [{ field: 'hasWithholding', op: 'eq', value: true }] },
    deadline: { kind: 'fixedDate', month: 1, day: 31, yearsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Modelo 10', description: 'Declaração anual de rendimentos e retenções' },
      en: { name: 'Modelo 10', description: 'Annual income and withholding return' },
    },
  },
  {
    code: 'MODEL_30_NON_RESIDENT_PAYMENTS',
    authority: 'TAX',
    periodicity: 'MONTHLY',
    legalRef: 'CIRC art. 119.º',
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'lastDayOfMonthAfterPeriodEnd', monthsAfter: 2 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Modelo 30', description: 'Rendimentos pagos ou devidos a não residentes' },
      en: { name: 'Modelo 30', description: 'Payments made to non-residents' },
    },
  },
  {
    code: 'INVENTORY_REPORTING',
    authority: 'TAX',
    periodicity: 'ANNUAL',
    legalRef: 'CIVA art. 29.º',
    appliesWhen: { all: [{ field: 'kind', op: 'eq', value: 'COMPANY' }] },
    deadline: { kind: 'fixedDate', month: 1, day: 31, yearsAfter: 1 },
    businessDayShift: 'NEXT',
    validFrom: VALID_FROM,
    validTo: null,
    i18n: {
      pt: { name: 'Comunicação de inventários', description: 'Inventário valorizado reportado à AT' },
      en: { name: 'Comunicação de inventários', description: 'Year-end inventory reporting' },
    },
  },
]
